
services:
  nextjs:
    build:
      context: ./frontend  # Next.js 프로젝트의 Dockerfile 경로
      dockerfile: Dockerfile  # Next.js 프로젝트의 Dockerfile 이름
    ports:
      - "3000:3000"  # Next.js 애플리케이션이 Listen하는 포트
    volumes:
      - ./frontend:/usr/src/app  # 호스트 파일 시스템과 컨테이너를 마운트하여 코드 변경 사항을 반영

  nestjs:
    build:
      context: ./backend  # Nest.js 프로젝트의 Dockerfile 경로
      dockerfile: Dockerfile  # Nest.js 프로젝트의 Dockerfile 이름
    ports:
      - "4242:4242"  # Nest.js 애플리케이션이 Listen하는 포트
    volumes:
      - ./backend:/usr/src/app  # 호스트 파일 시스템과 컨테이너를 마운트하여 코드 변경 사항을 반영
